### ISSUE TITLE
A way to disable cache and read directly from file

### ISSUE THREAD

**Issue by izakhearn** [fiddyschmitt/clonezilla-util#17]
Hi I was wondering if there is a way for me to read the image file directly without needing cache. 

I am trying to open a large backup but don't have a drive large enough to cache all the data on

**Comment by fiddyschmitt** [comment]
Hi Izak,

Unfortunately none of the compression formats available in Clonezilla support seeking, which is why it's necessary to extract (and cache) the content first. I have [asked](https://github.com/stevenshiau/clonezilla/issues/76) Steven over at Clonezilla to consider a seekable format, but it's a big change and may not get traction.

What compression format does your image use? (Please post a screenshot if unsure). I may be able to help if it's GZip.

Thanks!
Fidel

**Comment by izakhearn** [comment]
Hi Sorry I am responding only now. 

I think we used Gzip.

**Comment by fiddyschmitt** [comment]
Thanks, I'll put something together for you which creates a much smaller cache file.

**Comment by izakhearn** [comment]
Thanks so much. I have been trying to just recover password saved to
Firefox on it but has been taking forever to 1 build the cache and then 2
being unable to find a drive big enough to take the cache

**Comment by fiddyschmitt** [comment]
:) No worries!
I'm just running automated tests now. I'll upload the new version tonight (~in about 12 hours)

**Comment by fiddyschmitt** [comment]
Hi Izak,

I've created v2.0.1, available here: https://github.com/fiddyschmitt/clonezilla-util/releases/tag/v2.0.1

It uses gztool to make a much smaller cache.

Please let me know how it goes :)

Cheers,
Fidel

**Comment by izakhearn** [comment]
Hi Fiddyschmitt/Clonezilla-Util

This worked perfectly. I was able to get the system to mount the images and
get the data that I needed back. Thanks so much

**Comment by fiddyschmitt** [comment]
That's awesome!! Thanks Izack, my pleasure :)
